### ISSUE TITLE
Ripple-mixin error when updating ember-paper

### ISSUE THREAD

**Issue by Cabrafull** [Subtletree/ember-paper-link#12]
I'm getting this error when updating ember-paper from v1.0.0-beta.26 to newer releases
`Uncaught Error: Could not find module 'ember-paper/mixins/ripple-mixin' imported from 'ember-paper-link/components/paper-link'`

![image](https://user-images.githubusercontent.com/54360251/77681035-8adec980-6f73-11ea-8ee2-570830370e55.png)

Maybe because of this? From v1.0.0-beta.27 changelog

> replace RippleMixin with a `<PaperRipple/>` component

https://github.com/miguelcobain/ember-paper/blob/master/CHANGELOG.md#100-beta27

**Comment by lele-melis** [comment]
+1

**Comment by beastmst** [comment]
+1

**Comment by Subtletree** [comment]
Sorry guys I will sort this one tonight

**Comment by Subtletree** [comment]
Fixed with [v1.0.0](https://github.com/Subtletree/ember-paper-link/releases/tag/1.0.0)
