### ISSUE TITLE
How to define paper-link parameter

### ISSUE THREAD

**Issue by bloodknight2010** [Subtletree/ember-paper-link#2]
I would like to create paper link params.Eg.{{#paper-link-item 'index' }} How to define dynamic parameter. Pls help me.

**Comment by Subtletree** [comment]
Which dynamic params do you mean?

Like `{{#paper-link-item 'posts' post}}`?

**Comment by bloodknight2010** [comment]
Yes like this. {{#paper-link-item 'index' id }}

**Comment by Subtletree** [comment]
That should work as described in the readme.

Here's a working twiddle 🙂 
https://ember-twiddle.com/91d3ebac395c5ac4bbe596f7716d45a9?openFiles=templates.application.hbs%2C&route=%2F3

**Comment by bloodknight2010** [comment]
Thanks U very much.
