### ISSUE TITLE
Add information about recommended way

### ISSUE THREAD

**Issue by n1ru4l** [Subtletree/ember-paper-link#5]
@miguelcobain recommends the following method:

https://github.com/miguelcobain/ember-paper/issues/203#issuecomment-317150800

So maybe the README should state, that users might not need this addon?

**Comment by Subtletree** [comment]
`href-to` doesn't support active state classes (highlighting when that route is active) which is the main use case for this addon.

It's definitely possible to do this:
(requires an `eq` helper, access to `currentRouteName` and some active state styling for `paper-item`s)
```
{{#paper-button href=(href-to "posts.new") disabled=(eq "posts.new" currentRouteName)}}
  New Post
{{/paper-button}}
```
The below is essentially just a shortcut for the above
```
{{#paper-link "posts.new"}}
  New Post
{{/paper-link}}
```

The reason for using `href-to` is it's significant performance increase over `link-to`. So it could be good to mention in the readme about considering `href-to` if you need dozens or more links on a page?

**Comment by Subtletree** [comment]
Your question does give me some ideas though. e.g. this addon could move to using `href-to` under the hood. Would be especially easy in Ember 2.15 when the router service lands.

The most integrated solution is to update `paper-button` and `paper-item` so if they are passed an `href` then the active state is also calculated and applied.

**Comment by n1ru4l** [comment]
That would be awesome. As a result this library would not have to ship additional stylesheets. There is also a router polyfill available.

**Comment by miguelcobain** [comment]
Maybe this could help: https://balinterdi.com/blog/generate-urls-with-the-ember-router-service/

**Comment by Subtletree** [comment]
Added a notice to the readme for now. Still keen to look into the options mentioned above when I get the time
