### ISSUE TITLE
sass error $base_color and extend button.md-no-style;

### ISSUE THREAD

**Issue by beastmst** [Subtletree/ember-paper-link#8]
ember sass is complaint that 

Sass Syntax Error (SassCompiler) in app/styles/ember-paper-link.scss:8:12
 
 Error: Undefined variable: "$base-color".
  on line 8 of tmp/sass_compiler-input_base_path-C0NhAbtv.tmp/app/styles/ember-paper-link.scss
       from line 8 of tmp/sass_compiler-input_base_path-C0NhAbtv.tmp/app/styles/app.scss
>>     color: $base-color!important;
 
  -----------^

AND

Sass Syntax Error (SassCompiler) in /app/styles/ember-paper-link.scss:14:11
 
 Error: compound selectors may longer be extended.
Consider `@extend button, .md-no-style` instead.
See http://bit.ly/ExtendCompound for details.
 
@extend button.md-no-style;
               ^^^^^^^^^^^^^^^^^^
tmp/sass_compiler-input_base_path-QFXkayAB.tmp/app/styles/ember-paper-link.scss 14:11  root stylesheet

can help to fix?

**Comment by Subtletree** [comment]
Looks like something to do with sass changes in [recent ember-paper versions](https://github.com/miguelcobain/ember-paper/blob/master/CHANGELOG.md) and paper-link needs to catch up.

What ember-paper version are you using?

**Comment by beastmst** [comment]
"ember-cli-sass": "^8.0.1",
"ember-paper": "^1.0.0-beta.7"

**Comment by Tazrof** [comment]
For the missing base-color variable it comes from [this commit](https://github.com/miguelcobain/ember-paper/commit/05656311376bc4cd2adb64f036baded143d43937#diff-ec1a6b8fb86a4101a6a9be01af6c6be2L13).
As for the extend error I'm not familiar with SASS and Material.

**Comment by Subtletree** [comment]
Fixed in v0.0.6, sorry it took so long 😅
